/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UIModels;

import DatabaseConnnectivity.DBConnection;
import com.email.durgesh.Email;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Properties;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.mail.*;
import javax.mail.internet.*;
import javax.activation.*;

/**
 *
 * @author Vimantha_Dilshan
 */
public class Cashier extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Cashier() {
        initComponents();
    }

    Connection con;
    PreparedStatement pst;
    ResultSet rs;

    PreparedStatement pst2;
    ResultSet rs2;

    PreparedStatement pst3;
    ResultSet rs3;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtVehicleNo = new javax.swing.JTextField();
        txtCustomerName = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnHome = new javax.swing.JButton();
        txtCustomerEmail = new javax.swing.JTextField();
        txtCashierDate = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        txtEmpID = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtHours = new javax.swing.JSpinner();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtPartID = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtPartName = new javax.swing.JTextField();
        txtPartPrice = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        btnCashierEmployeeADD = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        txtPartTotal = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtPartQty = new javax.swing.JSpinner();
        btnStoreADD = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        txtPay = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtBalance = new javax.swing.JTextField();
        btnCashierBILL = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPrintedBill = new javax.swing.JTextArea();
        jSeparator6 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableCashier = new javax.swing.JTable();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtJobID = new javax.swing.JTextField();
        txtJobCharge = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        btnCashierJobsADD = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 96, 128));

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 1, 27)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 255));
        jLabel1.setText("RustREPAIR");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(242, 242, 242));

        jLabel2.setFont(new java.awt.Font("Prototype", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 96, 128));
        jLabel2.setText("CASHIER");

        jLabel3.setFont(new java.awt.Font("Abel", 0, 18)); // NOI18N
        jLabel3.setText("V.No");

        jLabel4.setFont(new java.awt.Font("Abel", 0, 18)); // NOI18N
        jLabel4.setText("Customer");

        jLabel5.setFont(new java.awt.Font("Abel", 0, 18)); // NOI18N
        jLabel5.setText("Date");

        txtVehicleNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVehicleNoActionPerformed(evt);
            }
        });

        txtCustomerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustomerNameActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Abel", 0, 18)); // NOI18N
        jLabel9.setText("Email");

        btnHome.setBackground(new java.awt.Color(0, 51, 102));
        btnHome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnHome.setForeground(new java.awt.Color(204, 204, 204));
        btnHome.setText("Home");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        txtCustomerEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustomerEmailActionPerformed(evt);
            }
        });

        txtCashierDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCashierDateActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel6.setFont(new java.awt.Font("Abel", 0, 18)); // NOI18N
        jLabel6.setText("EMP. ID");

        txtEmpID.setBackground(new java.awt.Color(253, 253, 211));
        txtEmpID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmpIDActionPerformed(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Working Employee");

        jLabel8.setFont(new java.awt.Font("Abel", 0, 18)); // NOI18N
        jLabel8.setText("Hours");

        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Parts Store");

        jLabel11.setFont(new java.awt.Font("Abel", 0, 18)); // NOI18N
        jLabel11.setText("Part ID");

        txtPartID.setBackground(new java.awt.Color(253, 253, 211));
        txtPartID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPartIDActionPerformed(evt);
            }
        });
        txtPartID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPartIDKeyPressed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Abel", 0, 18)); // NOI18N
        jLabel12.setText("Name");

        txtPartName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPartNameActionPerformed(evt);
            }
        });

        txtPartPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPartPriceActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Abel", 0, 18)); // NOI18N
        jLabel13.setText("Price");

        btnCashierEmployeeADD.setBackground(new java.awt.Color(3, 133, 90));
        btnCashierEmployeeADD.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnCashierEmployeeADD.setForeground(new java.awt.Color(204, 204, 255));
        btnCashierEmployeeADD.setText("SET");
        btnCashierEmployeeADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCashierEmployeeADDActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Abel", 0, 18)); // NOI18N
        jLabel14.setText("Total");

        txtPartTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPartTotalActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Abel", 0, 18)); // NOI18N
        jLabel15.setText("Qty");

        txtPartQty.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                txtPartQtyStateChanged(evt);
            }
        });

        btnStoreADD.setBackground(new java.awt.Color(3, 133, 90));
        btnStoreADD.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnStoreADD.setForeground(new java.awt.Color(204, 204, 255));
        btnStoreADD.setText("ADD");
        btnStoreADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStoreADDActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Abel", 1, 22)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 9, 17));
        jLabel16.setText("Balance");

        jLabel17.setFont(new java.awt.Font("Abel", 1, 22)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 9, 17));
        jLabel17.setText("Total");

        jLabel18.setFont(new java.awt.Font("Abel", 1, 22)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 9, 17));
        jLabel18.setText("Pay");

        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });

        txtPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPayActionPerformed(evt);
            }
        });

        jLabel19.setForeground(new java.awt.Color(102, 102, 102));
        jLabel19.setText("Bill");

        txtBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBalanceActionPerformed(evt);
            }
        });

        btnCashierBILL.setBackground(new java.awt.Color(169, 4, 53));
        btnCashierBILL.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnCashierBILL.setForeground(new java.awt.Color(204, 204, 204));
        btnCashierBILL.setText("BILL");
        btnCashierBILL.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnCashierBILL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCashierBILLActionPerformed(evt);
            }
        });

        txtPrintedBill.setColumns(20);
        txtPrintedBill.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        txtPrintedBill.setForeground(new java.awt.Color(51, 51, 51));
        txtPrintedBill.setRows(5);
        jScrollPane1.setViewportView(txtPrintedBill);

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);

        tableCashier.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Description", "Quantity", "Unit Price", "Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tableCashier);

        jLabel20.setFont(new java.awt.Font("Abel", 0, 26)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 51));
        jLabel20.setText("COME AGAIN");

        jLabel22.setFont(new java.awt.Font("Abel", 0, 26)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 51));
        jLabel22.setText("THANK YOU!");

        jLabel21.setForeground(new java.awt.Color(102, 102, 102));
        jLabel21.setText("Job");

        jLabel23.setFont(new java.awt.Font("Abel", 0, 18)); // NOI18N
        jLabel23.setText("Job ID");

        txtJobID.setBackground(new java.awt.Color(253, 253, 211));
        txtJobID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJobIDActionPerformed(evt);
            }
        });
        txtJobID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtJobIDKeyPressed(evt);
            }
        });

        txtJobCharge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJobChargeActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Abel", 0, 18)); // NOI18N
        jLabel24.setText("Amount");

        btnCashierJobsADD.setBackground(new java.awt.Color(3, 133, 90));
        btnCashierJobsADD.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnCashierJobsADD.setForeground(new java.awt.Color(204, 204, 255));
        btnCashierJobsADD.setText("ADD");
        btnCashierJobsADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCashierJobsADDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(30, 30, 30)
                        .addComponent(txtEmpID, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(txtHours, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7)
                    .addComponent(jLabel10)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addGap(37, 37, 37)
                                        .addComponent(txtTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel16)
                                            .addComponent(jLabel18))
                                        .addGap(12, 12, 12)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtPay, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                                            .addComponent(txtBalance)))
                                    .addComponent(jSeparator7, javax.swing.GroupLayout.Alignment.LEADING))
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel23)
                                        .addComponent(jLabel24))
                                    .addGap(16, 16, 16)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtJobID, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                                        .addComponent(txtJobCharge))
                                    .addGap(18, 18, 18)
                                    .addComponent(btnCashierJobsADD, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(36, 36, 36)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPartID, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPartPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtPartTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPartQty))
                            .addComponent(txtPartName, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnStoreADD, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnCashierEmployeeADD, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 591, Short.MAX_VALUE)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addComponent(jLabel21)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtVehicleNo, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(68, 68, 68)
                                .addComponent(jLabel9))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(236, 236, 236)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCashierDate, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCustomerEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel20))
                        .addGap(144, 144, 144)
                        .addComponent(btnHome)
                        .addGap(18, 18, 18)
                        .addComponent(btnCashierBILL, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(12, 12, 12)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(txtCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9)
                                    .addComponent(txtCustomerEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtVehicleNo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel5)
                                            .addComponent(txtCashierDate, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(txtEmpID, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnCashierEmployeeADD, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(txtHours, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(txtPartID, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12)
                                    .addComponent(txtPartName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(17, 17, 17)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtPartPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14)
                                    .addComponent(txtPartTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPartQty, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15)))
                            .addComponent(btnStoreADD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(14, 14, 14)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel21)
                        .addGap(5, 5, 5)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel23)
                                            .addComponent(txtJobID, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtJobCharge, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel24)))
                                    .addComponent(btnCashierJobsADD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(25, 25, 25)
                                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel19)
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel18)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel17))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtPay, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16)))
                            .addComponent(jScrollPane1))
                        .addGap(12, 12, 12))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jSeparator6)
                                .addContainerGap())
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jScrollPane2)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel22)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel20))
                                    .addComponent(btnCashierBILL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnHome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(22, 22, 22))))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPartPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPartPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPartPriceActionPerformed

    private void txtPartNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPartNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPartNameActionPerformed

    private void txtPartIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPartIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPartIDActionPerformed

    private void txtEmpIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmpIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmpIDActionPerformed

    private void txtCashierDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCashierDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCashierDateActionPerformed

    private void txtCustomerEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustomerEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustomerEmailActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Dashboard().setVisible(true);
    }//GEN-LAST:event_btnHomeActionPerformed

    private void txtCustomerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustomerNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustomerNameActionPerformed

    private void txtVehicleNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVehicleNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVehicleNoActionPerformed

    private void txtPartTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPartTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPartTotalActionPerformed

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

    private void txtPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPayActionPerformed

    private void txtBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBalanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBalanceActionPerformed

    private void btnCashierBILLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCashierBILLActionPerformed
        // Cashier BILL Button
        Balance();
        Bill();
             
        try {
            double Total = Double.parseDouble(txtTotal.getText().trim());
            double AmountPay = 0;
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/rustrepairpos", "root", "");
            
            
            if (con != null) {
                Statement s = con.createStatement();
                s.executeUpdate ("insert into Report values ('"+Total+"','"+AmountPay+"')");
                
                
            } else {
                JOptionPane.showMessageDialog(rootPane, "ERROR: Connection is NULL");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Employees.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Employees.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCashierBILLActionPerformed

    private void txtJobIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJobIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJobIDActionPerformed

    private void txtJobChargeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJobChargeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJobChargeActionPerformed

    public void Balance() {
        int SubTotal = Integer.parseInt(txtTotal.getText());
        int Pay = Integer.parseInt(txtPay.getText());

        int Bal = Pay - SubTotal;

        txtBalance.setText(String.valueOf(Bal));
    }

    public void Bill() {
        String SubTotal = txtTotal.getText();
        String Pay = txtPay.getText();
        String Bal = txtBalance.getText();

        DefaultTableModel model = new DefaultTableModel();
        model = (DefaultTableModel) tableCashier.getModel();

        DefaultTableModel model1 = new DefaultTableModel();
        model1 = (DefaultTableModel) tableCashier.getModel();

        txtPrintedBill.setText(txtPrintedBill.getText() + "**************************************\n");
        txtPrintedBill.setText(txtPrintedBill.getText() + "         Rust Repair (PVT) LTD        \n");
        txtPrintedBill.setText(txtPrintedBill.getText() + "               Colombo 5              \n");
        txtPrintedBill.setText(txtPrintedBill.getText() + "**************************************\n");

        txtPrintedBill.setText(txtPrintedBill.getText() + "Description" + "\t" + "Qty" + "\t" + "Unit" + "\t" + " Total" + "\n");

        int modelc = model.getRowCount();
        int model1c = model1.getRowCount();
        int rowcount = modelc + model1c;

        for (int h = 0; h < modelc; h++) {
            String JobDescription = (String) model1.getValueAt(h, 0);
            String JobQty = (String) model1.getValueAt(h, 1);
            String JobUnitprice = (String) model1.getValueAt(h, 2);
            String JobCharge = (String) model1.getValueAt(h, 3);

            txtPrintedBill.setText(txtPrintedBill.getText() + JobDescription + "\t" + JobQty + "\t" + JobUnitprice + "\t" + JobCharge + "\n");
            //For Job Description
        }

        for (int g = 0; g < model1c; g++) {
            String PartName = (String) model.getValueAt(g, 0);
            String PartQty = (String) model.getValueAt(g, 1);
            String PartPrice = (String) model.getValueAt(g, 2);
            String PartTotal = (String) model.getValueAt(g, 3);

            txtPrintedBill.setText(txtPrintedBill.getText() + PartName + "\t" + PartQty + "\t" + PartPrice + "\t" + PartTotal + "\n");
            //For Store Items
        }

        txtPrintedBill.setText(txtPrintedBill.getText() + "\n");
        txtPrintedBill.setText(txtPrintedBill.getText() + "\n");

        txtPrintedBill.setText(txtPrintedBill.getText() + "\t" + "\t" + "Subtotal: " + SubTotal +"\n");
        txtPrintedBill.setText(txtPrintedBill.getText() + "\t" + "\t" + "Pay: " + Pay +"\n");
        txtPrintedBill.setText(txtPrintedBill.getText() + "\t" + "\t" + "Balance: " + Bal +"\n");

        txtPrintedBill.setText(txtPrintedBill.getText() + "\n");
        txtPrintedBill.setText(txtPrintedBill.getText() + "--------------------------------------\n");
        txtPrintedBill.setText(txtPrintedBill.getText() + "          THANK YOU! COME AGAIN...    \n");
        txtPrintedBill.setText(txtPrintedBill.getText() + "--------------------------------------\n");

    }

    private void txtPartIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPartIDKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String PartID = txtPartID.getText();

            try {
                Class.forName("com.mysql.jdbc.Driver");
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/rustrepairpos", "root", "");
                pst = con.prepareStatement("select * from Store where PartID = ?");
                pst.setString(1, PartID);

                rs = pst.executeQuery();

                if (rs.next() == false) {
                    JOptionPane.showMessageDialog(this, "Product Code not found...");
                    //Check the product code is available in store database table
                    //if not, gives above message
                } else {
                    String PartName = rs.getString("PartName");
                    String PartPrice = rs.getString("PartPrice");

                    txtPartName.setText(PartName.trim());
                    txtPartPrice.setText(PartPrice.trim());
                }

            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Cashier.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(Cashier.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_txtPartIDKeyPressed

    private void txtPartQtyStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_txtPartQtyStateChanged
        // TODO add your handling code here:
        int PartQty = Integer.parseInt(txtPartQty.getValue().toString());
        int PartPrice = Integer.parseInt(txtPartPrice.getText());

        int tot = PartQty * PartPrice;
        txtPartTotal.setText(String.valueOf(tot));
    }//GEN-LAST:event_txtPartQtyStateChanged

    private void btnStoreADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStoreADDActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = new DefaultTableModel();

        model = (DefaultTableModel) tableCashier.getModel();
        model.addRow(new Object[]{
            txtPartName.getText(),
            txtPartQty.getValue().toString(),
            txtPartPrice.getText(),
            txtPartTotal.getText(),});

        int sum = 0;
        for (int i = 0; i < tableCashier.getRowCount(); i++) {
            sum = sum + Integer.parseInt(tableCashier.getValueAt(i, 3).toString());
        }

        txtTotal.setText(Integer.toString(sum));
        txtPartID.setText("");
        txtPartName.setText("");
        txtPartPrice.setText("");
        txtPartTotal.setText("");

    }//GEN-LAST:event_btnStoreADDActionPerformed

    private void txtJobIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtJobIDKeyPressed
        // Key Pressed Event in Job ID

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String JobID = txtJobID.getText();

            try {
                Class.forName("com.mysql.jdbc.Driver");
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/rustrepairpos", "root", "");
                pst2 = con.prepareStatement("select * from Jobs where JobID = ?");

                pst2.setString(1, JobID);
                rs2 = pst2.executeQuery();

                if (rs2.next() == false) {
                    JOptionPane.showMessageDialog(this, "JobID Not Found...");
                } else {
                    String JobCharge = rs2.getString("RCharge");
                    String JobDescription = "Repair Charge";
                    String JobQty = "-";
                    String JobUnitprice = "-";

                    txtJobCharge.setText(JobCharge.trim());
                }

            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Cashier.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(Cashier.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_txtJobIDKeyPressed

    private void btnCashierJobsADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCashierJobsADDActionPerformed
        // Cashier Jobs ADD Button
        String JobQty = "-";
        String JobUnitprice = "-";
        String JobDescription = "Repair Charge";

        DefaultTableModel model1 = new DefaultTableModel();

        model1 = (DefaultTableModel) tableCashier.getModel();
        model1.addRow(new Object[]{
            JobDescription,
            JobQty,
            JobUnitprice,
            txtJobCharge.getText(),}
        );

        int sum1 = 0;
        for (int m = 0; m < tableCashier.getRowCount(); m++) {
            sum1 = sum1 + Integer.parseInt(tableCashier.getValueAt(m, 3).toString());
        }

        txtTotal.setText(Integer.toString(+sum1));

        txtJobID.setText("");
        txtJobCharge.setText("");

    }//GEN-LAST:event_btnCashierJobsADDActionPerformed

    private void btnCashierEmployeeADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCashierEmployeeADDActionPerformed
        // Cashier Employee ADD Button

        String CustomerName = txtCustomerName.getText();
        String VehicleNo = txtVehicleNo.getText();
        String CashierDate = txtCashierDate.getText();
        String EmpID = txtEmpID.getText();
        int Hours = (Integer) txtHours.getValue();
        
        String To = txtCustomerEmail.getText();
        String From = "yeshf98@gmail.com";
        String Host = "localhost";
        
        /*Properties properties = System.getProperties();
                        
        properties.setProperty ("mail.stmp.auth", "true");
        properties.setProperty ("mail.stmp.starttls.enable", "true");
        properties.setProperty ("mail.stmp.host", "smtp.gmail.com");
        properties.setProperty ("mail.stmp.port", "587");
        
        Session session = Session.getDefaultInstance(properties, new javax.mail.Authenticator() {
            protected PasswordAuthentication getpasswordAuthentication() {
                return new PasswordAuthentication ("yeshf98@gmail.com","Annites18");
            }
        });
        
        try {
            MimeMessage message = new MimeMessage (session);
            message.setFrom (new InternetAddress(From));
            message.addRecipient(Message.RecipientType.TO,new InternetAddress(To));
            message.setSubject("Rust Repair Service Information");
            message.setText("Your Service is done now, Please do payments and grab your vehicle... Have a nice day!");
            Transport.send(message);
        } catch (MessagingException mex) {
            mex.printStackTrace();
        }*/
        
        //Connection Refused...
        


    }//GEN-LAST:event_btnCashierEmployeeADDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cashier().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCashierBILL;
    private javax.swing.JButton btnCashierEmployeeADD;
    private javax.swing.JButton btnCashierJobsADD;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnStoreADD;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTable tableCashier;
    private javax.swing.JTextField txtBalance;
    private javax.swing.JTextField txtCashierDate;
    private javax.swing.JTextField txtCustomerEmail;
    private javax.swing.JTextField txtCustomerName;
    private javax.swing.JTextField txtEmpID;
    private javax.swing.JSpinner txtHours;
    private javax.swing.JTextField txtJobCharge;
    private javax.swing.JTextField txtJobID;
    private javax.swing.JTextField txtPartID;
    private javax.swing.JTextField txtPartName;
    private javax.swing.JTextField txtPartPrice;
    private javax.swing.JSpinner txtPartQty;
    private javax.swing.JTextField txtPartTotal;
    private javax.swing.JTextField txtPay;
    private javax.swing.JTextArea txtPrintedBill;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtVehicleNo;
    // End of variables declaration//GEN-END:variables
}
