/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UIModels;

/**
 *
 * @author Vimantha_Dilshan
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnReport = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnCashier = new javax.swing.JButton();
        btnSpareParts = new javax.swing.JButton();
        btnEmployees = new javax.swing.JButton();
        btnRepairJobs = new javax.swing.JButton();
        btnSuppliers = new javax.swing.JButton();
        btnRestoration = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 96, 128));

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 1, 27)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 255));
        jLabel1.setText("RustREPAIR");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Developed byPeak Performers ");

        btnReport.setBackground(new java.awt.Color(255, 204, 255));
        btnReport.setForeground(new java.awt.Color(0, 0, 51));
        btnReport.setText("Report");
        btnReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnReport)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(242, 242, 242));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCashier.setBackground(new java.awt.Color(217, 217, 217));
        btnCashier.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        btnCashier.setForeground(new java.awt.Color(0, 96, 128));
        btnCashier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageResources/Cashier 96px.png"))); // NOI18N
        btnCashier.setText("CASHIER");
        btnCashier.setBorder(null);
        btnCashier.setMaximumSize(new java.awt.Dimension(100, 100));
        btnCashier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCashierActionPerformed(evt);
            }
        });
        jPanel2.add(btnCashier, new org.netbeans.lib.awtextra.AbsoluteConstraints(763, 240, 284, 167));

        btnSpareParts.setBackground(new java.awt.Color(217, 217, 217));
        btnSpareParts.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        btnSpareParts.setForeground(new java.awt.Color(0, 96, 128));
        btnSpareParts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageResources/Parts 96px.png"))); // NOI18N
        btnSpareParts.setText("STORE");
        btnSpareParts.setBorder(null);
        btnSpareParts.setMaximumSize(new java.awt.Dimension(100, 100));
        btnSpareParts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSparePartsMouseClicked(evt);
            }
        });
        btnSpareParts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSparePartsActionPerformed(evt);
            }
        });
        jPanel2.add(btnSpareParts, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 39, 284, 167));

        btnEmployees.setBackground(new java.awt.Color(217, 217, 217));
        btnEmployees.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        btnEmployees.setForeground(new java.awt.Color(0, 96, 128));
        btnEmployees.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageResources/Employee 96px.png"))); // NOI18N
        btnEmployees.setText("EMPLOYEES");
        btnEmployees.setBorder(null);
        btnEmployees.setMaximumSize(new java.awt.Dimension(100, 100));
        btnEmployees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmployeesActionPerformed(evt);
            }
        });
        jPanel2.add(btnEmployees, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 40, 284, 167));

        btnRepairJobs.setBackground(new java.awt.Color(217, 217, 217));
        btnRepairJobs.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        btnRepairJobs.setForeground(new java.awt.Color(0, 96, 128));
        btnRepairJobs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageResources/Repair 96px.png"))); // NOI18N
        btnRepairJobs.setText("REPAIR JOBS");
        btnRepairJobs.setBorder(null);
        btnRepairJobs.setMaximumSize(new java.awt.Dimension(100, 100));
        btnRepairJobs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRepairJobsActionPerformed(evt);
            }
        });
        jPanel2.add(btnRepairJobs, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 240, 284, 167));

        btnSuppliers.setBackground(new java.awt.Color(217, 217, 217));
        btnSuppliers.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        btnSuppliers.setForeground(new java.awt.Color(0, 96, 128));
        btnSuppliers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageResources/Supplier 96px.png"))); // NOI18N
        btnSuppliers.setText("SUPPLIERS");
        btnSuppliers.setBorder(null);
        btnSuppliers.setMaximumSize(new java.awt.Dimension(100, 100));
        btnSuppliers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuppliersActionPerformed(evt);
            }
        });
        jPanel2.add(btnSuppliers, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 39, 284, 167));

        btnRestoration.setBackground(new java.awt.Color(217, 217, 217));
        btnRestoration.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btnRestoration.setForeground(new java.awt.Color(0, 96, 128));
        btnRestoration.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageResources/Restoration 96px.png"))); // NOI18N
        btnRestoration.setText("VEHICLE RESTORATION");
        btnRestoration.setBorder(null);
        btnRestoration.setMaximumSize(new java.awt.Dimension(100, 100));
        btnRestoration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestorationActionPerformed(evt);
            }
        });
        jPanel2.add(btnRestoration, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, 284, 167));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1137, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCashierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCashierActionPerformed
        // TODO add your handling code here:
        this.setVisible (false);
        new Cashier().setVisible(true);
    }//GEN-LAST:event_btnCashierActionPerformed

    private void btnRestorationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestorationActionPerformed
        // TODO add your handling code here:
        this.setVisible (false);
        new RestorationJobs().setVisible(true);
    }//GEN-LAST:event_btnRestorationActionPerformed

    private void btnRepairJobsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRepairJobsActionPerformed
        // TODO add your handling code here:
        this.setVisible (false);
        new RepairJobs().setVisible(true);
    }//GEN-LAST:event_btnRepairJobsActionPerformed

    private void btnEmployeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmployeesActionPerformed
        // TODO add your handling code here:
        this.setVisible (false);
        new Employees().setVisible(true);
    }//GEN-LAST:event_btnEmployeesActionPerformed

    private void btnSuppliersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuppliersActionPerformed
        // TODO add your handling code here:
        this.setVisible (false);
        new Suppliers().setVisible(true);
    }//GEN-LAST:event_btnSuppliersActionPerformed

    private void btnSparePartsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSparePartsActionPerformed
        // TODO add your handling code here:
        this.setVisible (false);
        new SpareParts().setVisible(true);
    }//GEN-LAST:event_btnSparePartsActionPerformed

    private void btnSparePartsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSparePartsMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSparePartsMouseClicked

    private void btnReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportActionPerformed
        // TODO add your handling code here:
        this.setVisible (false);
        new Report().setVisible(true);
    }//GEN-LAST:event_btnReportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Dashboard().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCashier;
    private javax.swing.JButton btnEmployees;
    private javax.swing.JButton btnRepairJobs;
    private javax.swing.JButton btnReport;
    private javax.swing.JButton btnRestoration;
    private javax.swing.JButton btnSpareParts;
    private javax.swing.JButton btnSuppliers;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
