/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UIModels;
import DatabaseConnnectivity.DBConnection;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

/**
 *
 * @author Vimantha_Dilshan
 */
public class RestorationJobs extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public RestorationJobs() {
        initComponents();
    }
    
    ResultSet rs;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtJobID = new javax.swing.JTextField();
        txtEmpName = new javax.swing.JTextField();
        txtCustomerName = new javax.swing.JTextField();
        txtCustomerTelephone = new javax.swing.JTextField();
        txtCustomerAddress = new javax.swing.JTextField();
        btnRestorationJobsUPDATE = new javax.swing.JButton();
        btnRestorationJobsREMOVE = new javax.swing.JButton();
        btnRestorationJobsADD = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        txtVehicleType = new javax.swing.JComboBox<>();
        txtVehicleNo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtRestoreDate = new javax.swing.JTextField();
        txtRestoreCharge = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 96, 128));

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 1, 27)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 255));
        jLabel1.setText("RustREPAIR");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(11, 11, 11))
        );

        jPanel2.setBackground(new java.awt.Color(242, 242, 242));

        jLabel2.setFont(new java.awt.Font("Prototype", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 96, 128));
        jLabel2.setText("RESTORATION JOBS MANAGEMENT");

        jLabel3.setFont(new java.awt.Font("Abel", 0, 18)); // NOI18N
        jLabel3.setText("Employee");

        jLabel4.setFont(new java.awt.Font("Abel", 0, 18)); // NOI18N
        jLabel4.setText("Job ID");

        jLabel5.setFont(new java.awt.Font("Abel", 0, 18)); // NOI18N
        jLabel5.setText("Customer Name");

        jLabel6.setFont(new java.awt.Font("Abel", 0, 18)); // NOI18N
        jLabel6.setText("Customer Address");

        jLabel7.setFont(new java.awt.Font("Abel", 0, 18)); // NOI18N
        jLabel7.setText("Customer Telephone");

        txtJobID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJobIDActionPerformed(evt);
            }
        });
        txtJobID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtJobIDKeyPressed(evt);
            }
        });

        txtEmpName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmpNameActionPerformed(evt);
            }
        });

        txtCustomerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustomerNameActionPerformed(evt);
            }
        });

        txtCustomerTelephone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustomerTelephoneActionPerformed(evt);
            }
        });

        txtCustomerAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustomerAddressActionPerformed(evt);
            }
        });

        btnRestorationJobsUPDATE.setBackground(new java.awt.Color(0, 102, 102));
        btnRestorationJobsUPDATE.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnRestorationJobsUPDATE.setForeground(new java.awt.Color(204, 204, 204));
        btnRestorationJobsUPDATE.setText("UPDATE");
        btnRestorationJobsUPDATE.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnRestorationJobsUPDATE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestorationJobsUPDATEActionPerformed(evt);
            }
        });

        btnRestorationJobsREMOVE.setBackground(new java.awt.Color(169, 4, 53));
        btnRestorationJobsREMOVE.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnRestorationJobsREMOVE.setForeground(new java.awt.Color(204, 204, 204));
        btnRestorationJobsREMOVE.setText("REMOVE");
        btnRestorationJobsREMOVE.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnRestorationJobsREMOVE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestorationJobsREMOVEActionPerformed(evt);
            }
        });

        btnRestorationJobsADD.setBackground(new java.awt.Color(8, 110, 52));
        btnRestorationJobsADD.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnRestorationJobsADD.setForeground(new java.awt.Color(204, 204, 204));
        btnRestorationJobsADD.setText("ADD");
        btnRestorationJobsADD.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnRestorationJobsADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestorationJobsADDActionPerformed(evt);
            }
        });

        btnHome.setBackground(new java.awt.Color(0, 51, 102));
        btnHome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnHome.setForeground(new java.awt.Color(204, 204, 204));
        btnHome.setText("Home");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel8.setFont(new java.awt.Font("Abel", 0, 18)); // NOI18N
        jLabel8.setText("Vehicle Type");

        txtVehicleType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Select>", "Car [Hatchback]", "Car [Sedan]", "SUV", "Lorry", "Truck", "Mini Truck", "Van", "Campervan", "Motor Bicycle", "Other" }));
        txtVehicleType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVehicleTypeActionPerformed(evt);
            }
        });

        txtVehicleNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVehicleNoActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Abel", 0, 18)); // NOI18N
        jLabel9.setText("Vehicle No");

        jLabel10.setFont(new java.awt.Font("Abel", 0, 18)); // NOI18N
        jLabel10.setText("Date");

        txtRestoreDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRestoreDateActionPerformed(evt);
            }
        });

        txtRestoreCharge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRestoreChargeActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Abel", 0, 18)); // NOI18N
        jLabel11.setText("Charge (Rs.)");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8)
                            .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtCustomerAddress, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCustomerTelephone, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCustomerName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEmpName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtVehicleType, 0, 261, Short.MAX_VALUE)
                            .addComponent(txtJobID, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(75, 75, 75)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtVehicleNo, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(btnRestorationJobsUPDATE, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                                .addComponent(btnRestorationJobsREMOVE, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnRestorationJobsADD, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtRestoreDate, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtRestoreCharge, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(87, 87, 87))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtVehicleNo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtRestoreDate, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtRestoreCharge, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnRestorationJobsUPDATE, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnRestorationJobsREMOVE, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(btnRestorationJobsADD, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8)
                                    .addComponent(txtVehicleType, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(txtJobID, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(19, 19, 19)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(txtEmpName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(21, 21, 21)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(txtCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(txtCustomerTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(txtCustomerAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(btnHome)
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmpNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmpNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmpNameActionPerformed

    private void txtCustomerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustomerNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustomerNameActionPerformed

    private void txtCustomerTelephoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustomerTelephoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustomerTelephoneActionPerformed

    private void txtCustomerAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustomerAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustomerAddressActionPerformed

    private void btnRestorationJobsUPDATEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestorationJobsUPDATEActionPerformed
        // UPDATE Button (Restoration Jobs UI)
        try {
            String VehicleType = txtVehicleType.getSelectedItem().toString().trim();
            String JobID = txtJobID.getText().trim();
            String EmpName = txtEmpName.getText().trim();
            String CustomerName = txtCustomerName.getText().trim();
            String CustomerTelephone = txtCustomerTelephone.getText().trim();
            String CustomerAddress = txtCustomerAddress.getText().trim();
            String VehicleNo = txtVehicleNo.getText().trim();
            String RestoreDate = txtRestoreDate.getText().trim();
            double RestoreCharge = Double.parseDouble(txtRestoreCharge.getText().trim());

            String RepairJCategory = "None";
            //This variable not belongs to this category
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/rustrepairpos", "root", "");
            
            if (con != null) {
                Statement s = con.createStatement();
                s.executeUpdate ("Update Jobs set RepairCategory='"+RepairJCategory+"',VehicleType='"+VehicleType+"',EmpName='"+EmpName+"',CustomerName='"+CustomerName+"',CustomerTelephone='"+CustomerTelephone+"',CustomerAddress='"+CustomerAddress+"',VehicleNo='"+VehicleNo+"',RDate='"+RestoreDate+"',RCharge='"+RestoreCharge+"' where JobID='"+JobID+"'");
                JOptionPane.showMessageDialog(null, "If you enter valid Job ID, Update is Succesful...");
                
                txtVehicleType.setSelectedItem("<Select>");
                txtJobID.setText("");
                txtEmpName.setText("");
                txtCustomerName.setText("");
                txtCustomerTelephone.setText("");
                txtCustomerAddress.setText("");
                txtVehicleNo.setText("");
                txtRestoreDate.setText("");
                txtRestoreCharge.setText("");
                
                
            } else {
                JOptionPane.showMessageDialog(rootPane, "ERROR: Connection is NULL");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Employees.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Employees.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRestorationJobsUPDATEActionPerformed

    private void btnRestorationJobsREMOVEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestorationJobsREMOVEActionPerformed
        // REMOVE Button (Restoration Jobs UI)
        try {
            String VehicleType = txtVehicleType.getSelectedItem().toString().trim();
            String JobID = txtJobID.getText().trim();
            String EmpName = txtEmpName.getText().trim();
            String CustomerName = txtCustomerName.getText().trim();
            String CustomerTelephone = txtCustomerTelephone.getText().trim();
            String CustomerAddress = txtCustomerAddress.getText().trim();
            String VehicleNo = txtVehicleNo.getText().trim();
            String RestoreDate = txtRestoreDate.getText().trim();
            double RestoreCharge = Double.parseDouble(txtRestoreCharge.getText().trim());

            String RepairJCategory = "None";
            //This variable not belongs to this category
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/rustrepairpos", "root", "");
            
            if (con != null) {
                Statement s = con.createStatement();
                s.executeUpdate ("delete from Jobs where JobID='"+JobID+"'");
                JOptionPane.showMessageDialog(null, "Remove Succesfully...");
                
                txtVehicleType.setSelectedItem("<Select>");
                txtJobID.setText("");
                txtEmpName.setText("");
                txtCustomerName.setText("");
                txtCustomerTelephone.setText("");
                txtCustomerAddress.setText("");
                txtVehicleNo.setText("");
                txtRestoreDate.setText("");
                txtRestoreCharge.setText("");
                
            } else {
                JOptionPane.showMessageDialog(rootPane, "ERROR: Connection is NULL");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Employees.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Employees.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRestorationJobsREMOVEActionPerformed

    private void txtJobIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJobIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJobIDActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        this.setVisible (false);
        new Dashboard().setVisible(true);
    }//GEN-LAST:event_btnHomeActionPerformed

    private void txtVehicleTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVehicleTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVehicleTypeActionPerformed

    private void txtVehicleNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVehicleNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVehicleNoActionPerformed

    private void txtRestoreDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRestoreDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRestoreDateActionPerformed

    private void txtRestoreChargeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRestoreChargeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRestoreChargeActionPerformed

    private void btnRestorationJobsADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestorationJobsADDActionPerformed
        // ADD Button (Restoration UI)
        try {
            String VehicleType = txtVehicleType.getSelectedItem().toString().trim();
            String JobID = txtJobID.getText().trim();
            String EmpName = txtEmpName.getText().trim();
            String CustomerName = txtCustomerName.getText().trim();
            String CustomerTelephone = txtCustomerTelephone.getText().trim();
            String CustomerAddress = txtCustomerAddress.getText().trim();
            String VehicleNo = txtVehicleNo.getText().trim();
            String RestoreDate = txtRestoreDate.getText().trim();
            double RestoreCharge = Double.parseDouble(txtRestoreCharge.getText().trim());

            String RepairJCategory = "None";
            //This variable not belongs to this category
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/rustrepairpos", "root", "");
            
            if (con != null) {
                Statement s = con.createStatement();
                s.executeUpdate ("insert into Jobs values ('"+JobID+"','"+RepairJCategory+"','"+VehicleType+"','"+EmpName+"','"+CustomerName+"','"+CustomerTelephone+"','"+CustomerAddress+"','"+VehicleNo+"','"+RestoreDate+"','"+RestoreCharge+"')");
                JOptionPane.showMessageDialog(null, "Added Succesfully...");
                
                txtVehicleType.setSelectedItem("<Select>");
                txtJobID.setText("");
                txtEmpName.setText("");
                txtCustomerName.setText("");
                txtCustomerTelephone.setText("");
                txtCustomerAddress.setText("");
                txtVehicleNo.setText("");
                txtRestoreDate.setText("");
                txtRestoreCharge.setText("");
                
            } else {
                JOptionPane.showMessageDialog(rootPane, "ERROR: Connection is NULL");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Employees.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Employees.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRestorationJobsADDActionPerformed

    private void txtJobIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtJobIDKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String JobID = txtJobID.getText();
            
            try {
                Class.forName("com.mysql.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/rustrepairpos", "root", "");
                PreparedStatement pst = con.prepareStatement ("select * from Jobs where JobID = ?");
                
                pst.setString(1, JobID);
                rs = pst.executeQuery();
                
                if (rs.next() == true) {
                    String VehicleType = rs.getString("VehicleType");
                    String EmpName = rs.getString("EmpName");
                    String CustomerName = rs.getString("CustomerName");
                    String CustomerTelephone = rs.getString("CustomerTelephone");
                    String CustomerAddress = rs.getString("CustomerAddress");
                    String VehicleNo = rs.getString("VehicleNo");
                    String RestoreDate = rs.getString("RDate");
                    String RestoreCharge = rs.getString("RCharge");
                    
                    txtVehicleType.setSelectedItem(VehicleType.trim());
                    txtEmpName.setText(EmpName.trim());
                    txtCustomerName.setText(CustomerName.trim());
                    txtCustomerTelephone.setText(CustomerTelephone.trim());
                    txtCustomerAddress.setText(CustomerAddress.trim());
                    txtVehicleNo.setText(VehicleNo.trim());
                    txtRestoreDate.setText(RestoreDate.trim());
                    txtRestoreCharge.setText(RestoreCharge.trim());
                    
                }
                
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(RestorationJobs.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(RestorationJobs.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }    
    }//GEN-LAST:event_txtJobIDKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RestorationJobs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RestorationJobs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RestorationJobs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RestorationJobs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RestorationJobs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnRestorationJobsADD;
    private javax.swing.JButton btnRestorationJobsREMOVE;
    private javax.swing.JButton btnRestorationJobsUPDATE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtCustomerAddress;
    private javax.swing.JTextField txtCustomerName;
    private javax.swing.JTextField txtCustomerTelephone;
    private javax.swing.JTextField txtEmpName;
    private javax.swing.JTextField txtJobID;
    private javax.swing.JTextField txtRestoreCharge;
    private javax.swing.JTextField txtRestoreDate;
    private javax.swing.JTextField txtVehicleNo;
    private javax.swing.JComboBox<String> txtVehicleType;
    // End of variables declaration//GEN-END:variables
}
